package spaxel.entity.storage.item;

public enum ItemName {
    BASIC_LASER,
    PIERCING_LASER,
    DISRUPT_LASER,
    SLOWING_LASER,
    BASIC_MISSILE,
    CLUSTER_MISSILE,
    HACKING_MISSILE,
    HOMING_MISSILE,
    BASIC_SHIELD,
    ACTIVE_SHIELD,
    ANTI_SHIELD,
    FORCE_SHIELD
}
