load("//bazel:macros.bzl", "cg_java_library")

package(default_visibility = ["//games/spaxel:__subpackages__"])

cg_java_library(
    name = "logger",
    srcs = glob(["*.java"]),
    deps = ["//games/spaxel/src/system:system_type"],
)
